apiVersion: v1
kind: Service
metadata:
  name: composed-nodeport
  labels:
    app: composed
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: web
    nodePort: 31000
  selector:
    app: composed